

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
        - ./docker/mariadb:/var/lib/mysql/
    ports:
      - ${MARIDB_PORT:-3306}:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT:-8080}:8080




